# Envoy templating values
global:
  appName: "tracker-simulator-envoy-nextgen"
  networkHost: "10.0.0.16"
  envoy:
    host: "10.0.0.16"
    serviceType: LoadBalancer
    envoyPorts:
      trackerServerGoPort: 32016
      trackerServerTlsGoPort: 30599
      trackerServerQuicGoPort: 30389
      trackerClientGoPort: 32531
      trackerAnalyticsPort: 30313
      communicationsAppPort: 32326
    appPorts:
      trackerServerGoPort: 18098
      trackerServerTlsGoPort: 8098
      trackerServerQuicGoPort: 8444
      trackerClientGoPort: 8099
      trackerAnalyticsPort: 5050
      communicationsAppPort: 80
