apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: custom-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bare-metal-gateway
  namespace: default
spec:
  gatewayClassName: eg
  listeners:
  - name: tracker-client-go
    protocol: TCP
    port: {{ .Values.global.envoy.appPorts.trackerClientGoPort }}
  - name: tracker-server-go
    protocol: TCP
    port: {{ .Values.global.envoy.appPorts.trackerServerGoPort }}
  - name: tracker-server-go-http3
    protocol: UDP
    port: {{ .Values.global.envoy.appPorts.trackerServerTlsGoPort }}
  - name: tracker-server-go-quic
    protocol: UDP
    port: {{ .Values.global.envoy.appPorts.trackerServerQuicGoPort }}
    allowedRoutes:
      kinds:
      - kind: UDPRoute
  - name: tracker-analytics
    protocol: TCP
    port: {{ .Values.global.envoy.appPorts.trackerAnalyticsPort }}
  - name: communications-app
    protocol: TCP
    port: {{ .Values.global.envoy.appPorts.communicationsAppPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tracker-client-go-route
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: tracker-client-go
  rules:
  - backendRefs:
    - name: trackerclient-go
      port: {{ .Values.global.envoy.appPorts.trackerClientGoPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tracker-server-go-route-http1
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: tracker-server-go
  rules:
  - backendRefs:
    - name: trackerserver-go
      port: {{ .Values.global.envoy.appPorts.trackerServerGoPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: tracker-server-go-route-http3
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: tracker-server-go-http3
  rules:
  - backendRefs:
    - name: trackerserver-go
      port: {{ .Values.global.envoy.appPorts.trackerServerTlsGoPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: tracker-server-go-route-quic
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: tracker-server-go-quic
  rules:
  - backendRefs:
    - name: trackerserver-go
      port: {{ .Values.global.envoy.appPorts.trackerServerQuicGoPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: tracker-analytics-route
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: tracker-analytics
  rules:
  - backendRefs:
    - name: trackeranalytics
      port: {{ .Values.global.envoy.appPorts.trackerAnalyticsPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: communications-app-route
  namespace: default
spec:
  parentRefs:
  - name: bare-metal-gateway
    sectionName: communications-app
  rules:
  - backendRefs:
    - name: communications-app
      port: {{ .Values.global.envoy.appPorts.communicationsAppPort }}      
{{ if eq .Values.global.envoy.serviceType "NodePort" }}      
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: {{ .Values.global.envoy.serviceType }}
        externalTrafficPolicy: Cluster
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
              - name: tracker-client-go
                nodePort: {{ .Values.global.envoy.envoyPorts.trackerClientGoPort }}
                port: {{ .Values.global.envoy.appPorts.trackerClientGoPort }}
                protocol: TCP
              - name: tracker-server-go
                nodePort: {{ .Values.global.envoy.envoyPorts.trackerServerGoPort }}
                port: {{ .Values.global.envoy.appPorts.trackerServerGoPort }}
                protocol: TCP
              - name: tracker-server-go-http3
                nodePort: {{ .Values.global.envoy.envoyPorts.trackerServerTlsGoPort }}
                port: {{ .Values.global.envoy.appPorts.trackerServerTlsGoPort }}
                protocol: UDP
              - name: tracker-server-go-quic
                nodePort: {{ .Values.global.envoy.envoyPorts.trackerServerQuicGoPort }}
                port: {{ .Values.global.envoy.appPorts.trackerServerQuicGoPort }}
                protocol: UDP
              - name: tracker-analytics
                nodePort: {{ .Values.global.envoy.envoyPorts.trackerAnalyticsPort }}
                port: {{ .Values.global.envoy.appPorts.trackerAnalyticsPort }}
                protocol: TCP
              - name: communications-app
                nodePort: {{ .Values.global.envoy.envoyPorts.communicationsAppPort }}
                port: {{ .Values.global.envoy.appPorts.communicationsAppPort }}
                protocol: TCP
{{ else if eq .Values.global.envoy.serviceType "LoadBalancer" }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer
        externalTrafficPolicy: Cluster
{{ end }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: tracker-server-go-least-connections-http3
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: UDPRoute
    name: tracker-server-go-route-http3
  loadBalancer:
    type: LeastRequest
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: tracker-server-go-least-connections-quic
  namespace: default
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: UDPRoute
    name: tracker-server-go-route-quic
  loadBalancer:
    type: LeastRequest        